import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { SignUp } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";
import {User} from  "@prisma/client"

export default function Home() {
  const hello = api.user.hello.useQuery({ text: "from Selma" });
  const ctx = api.useContext();
  const usersResponse=api.user.getAll.useQuery().data;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
    
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>

          <ul>
  {usersResponse !== undefined && usersResponse !== null ? (
    usersResponse.users.map((user: User) => (
      <li key={user.id}>{user.name}</li>
    ))
  ) : (
    <li>No users available</li>
  )}
</ul>

      
     </main>
    </>
  );
}
